version: '2'
services:
  mlbtv:
    build: .
    volumes:
      - ./config:/root/.config/mlbstreamer
      - ./videos:/videos
    working_dir: /videos
    environment:
      - BASEURL=http://vimes.coloti.se/~mattiasa/mlb/
# Set this to only get the audio
#      - NOVIDEO=1
