version: '2'
services:
  mlbtv:
    build: .
    volumes:
      - ./config:/root/.mlb
      - /mattiasa/public_html/mlb:/videos
    working_dir: /videos
    environment:
      - BASEURL=http://vimes.coloti.se/~mattiasa/mlb/
